### PR TITLE
Momentum wheel desaturation

### PR DESCRIPTION
**Pull request by SamFayolle**

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Marie,

The unit test for the tidally locked rotation model fails for me (was it supposed to be in this pull request?), on a Spice error:

================================================================================
 
Toolkit version: N0065
 
SPICE(KERNELVARNOTFOUND) -- The Variable Was not Found in the Kernel Pool.
 
The variable BODY501_RADII could not be found in the kernel pool.
 
A traceback follows.  The name of the highest level module is first.
bodvrd_c --> BODVRD
 
Oh, by the way:  The SPICELIB error handling actions are USER-TAILORABLE.  You
can choose whether the Toolkit aborts or continues when errors occur, which
error messages to output, and where to send the output.  Please read the ERROR
"Required Reading" file, or see the routines ERRACT, ERRDEV, and ERRPRT.
 
================================================================================


 Does it work correctly for you?

Best,

Dominic

**Comment by mchambe** [comment]
Hi Dominic,

It was definitely not meant to be part of the pull request (it is also the test that I mentioned last Friday as failing on my Linux machine). I didn't pay attention to that but indeed it was on the branch I pulled from your repository so it becomes part of the pull request even if I initially only wanted to merge the deltaV momentum wheel desaturation code. I was planning to have a look at this test and see what is going on after finishing the modifications on the solar sailing radiation pressure model but I can do it before if you prefer?

Best, 

Marie

**Comment by DominicDirkx** [comment]
Hi Marie,

Ok, thanks. I'm pretty sure the source of the error is that this:

    tudat::spice_interface::loadStandardSpiceKernels( );

line is missing at the start of the test. If you update the code, and put in a better name for the rotation model, I see no reason why we couldn't merge this feature together with the desaturation code,

Dominic

**Comment by mchambe** [comment]
Hi Dominic,

I actually made some modifications to the synchronous rotation model on a separate local branch (adding comments and one missing unit test). So directly modifying the name of the rotational model and the failing unit test on this branch and creating a separate pull request might be a bit easier?
Or I can merge the two branches and create a unique pull request if you think it is a better solution?

Best,

Marie

**Comment by DominicDirkx** [comment]
Whichever one would be less work for you :)

**Comment by DominicDirkx** [comment]
Code has been merged, thanks!

**Pull request merged**
