### PR TITLE
Non Ideal Solar Sail Model

### PR DESCRIPTION
**Pull request by Sceki**
This PR aims to introduce the non-ideal solar sail model into Tudat.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Some interface modifications have been made, and code has been merged (#552). Many thanks for your work on this!

Dominic

**Comment by Sceki** [comment]
Hello, 

I just realized that by creating a separate PR you have removed me as a contributor.
Why is this the case?

Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacomo,

I can assure you that this was not intentional. My guess is that, in reorganizing your code, there was not an initial merge of your code followed by a reorganization. 

I'll see if there is a 'clean' way in which we can correct this. Otherwise, we will simply delete the current solar sail model files, and ask you to make a new pull request wil the final code. 

If you have not heard anything by the end of next week, please post here to remind us,

Best,

Domini

**Comment by Sceki** [comment]
Hello Dominic,

 any news about this?

Best,
Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacmo,

I haven't figured out a way to do this in the 'neat' way, so what we'll do is delete all your contributions, commit the removal, and then you can re-add everything in a separate pull request. Just so that we do it correctly in one go, could you provide a list of files (and parts of files) that are from you?

Best,

Dominic

**Comment by Sceki** [comment]
Hello,
isn't it enough that you re-open this PR and merge this (after pushing the changes you desire), after having added the changes you want? 

Kind regards,
Giacomo

**Comment by DominicDirkx** [comment]
Hi,

No, to merge your code we made some changes to the code's organization, as I think we briefly discussed once. So, please go through the code, let me know which parts are your contribution, and we'll get this sorted out,

Best,

Dominic

**Comment by Sceki** [comment]
Hello,

 all my contribution lines are here in this PR under the “changes” section, you can see my contribution there.

Kind regards 
Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacomo,

As I said, your contributions are now in different files (or at least some of them). So, please see my previous post, and let me know which lines in which files should be attributed to you,

Best,

Dominic

**Comment by Sceki** [comment]
Hello,

We are talking about going through >2000 lines of code and compare it with other >3000 to see which ones match or not. I, of course, do not have the time to do it. Moreover, I was not even responsible for this and I do not get why should I be the person fix it. 
Anyway, if nobody is willing to do this we can move on: it is more a matter of 'methods'.

Best,
Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacomo,

There's no need to take this tone. If the problem is that you do not want to take the time to do this, you could have said so from the start. 

Like I said, you deserve credit for the code that you wrote, and I want to make sure that you get it. If you're not willing to identify your lines of code, I'll make a best effort to do this -in the limited time that I have- to do this. But, I do not plan to iterate on this. So, I propose that:

- I make a new Tudat branch, and remove your code from it.
- I will send you the original files, and you can copy-paste these full files back in, and commit the code
- You open a pull request for this code, we merge it into the master, and you should show up as contributor.

If this works for you, let me know. If this would also cost you too much time, let me know,

Dominic

**Pull request closed without merging**
