### PR TITLE
Panelled radiation pressure

### PR DESCRIPTION
**Pull request by SamFayolle**

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Marie,

Thanks! Great to finally have this (almost) in Tudat. When running the panelled acceleration unit test, I'm getting some failures (see attached file)
[panelledRadiationPressureErrors.log](https://github.com/Tudat/tudat/files/3131211/panelledRadiationPressureErrors.log)

It seems that the accelerations are not zero in the case where they should be (although they are small). On further inspection, it seems that the code is failing for test case 3.

I'm assuming it passes for you under Windows. If you elaborate a bit more on how this test works, and what it tests, I can have a further look at why it's failing on Ubuntu,

Best,

Dominic

**Comment by mchambe** [comment]
Hi Dominic,
That is indeed weird, it does run on my computer but for some reason all the expected ("manually" calculated) SRP accelerations are equal to 0 in your case... I will have a close look and give you more details so that you can investigate it as well if I can't find what is going wrong.

Best, 
Marie

**Comment by mchambe** [comment]
It's a bit tricky to solve this from my Windows machine as the unit test is working fine for me, but would it be possible that it works now for you as well with the small modification I just pushed?

Marie

**Comment by mchambe** [comment]
I actually ran it on my old Linux machine and it seems to work now. I think it was because the "abs" function takes an integer as input and I wrongly used it with a double. But for some reason, it still worked on Window, so that I didn't notice it, while it yielded the error you saw on Linux. 

Best,
Marie

**Comment by DominicDirkx** [comment]
Hi Marie,

Thanks, I'll try to find the time today to run in on my computer :)

Dominic

**Comment by DominicDirkx** [comment]
Great, it passes now for me too. Well done! I think the code is almost ready to commit, I just have a few small comments:

- In the panelled radiation pressure tests, could you add (as comments, in the code or preceding the test) a few lines on what the different tests are, and wy?
- Could you define all floating point variables with e.g. 1.0 instead of 1? (there are a few in the panelled radiation pressure model)
- The code for the PanelledRadiationPressureInterface, PanelledRadiationPressurePartial and PanelledRadiationPressureInterfaceSettings classes are (partially) missing comments. For the get/set functions, there's no need to add /param or /return tags, just a single short line of Doxygen is fine. Also, the createPanelledRadiationPressureAcceleration function is missing a Doxygen comment

Best,

Dominic

**Comment by DominicDirkx** [comment]
Thanks, the added comments make everything much clearer. All unit tests pass, and the code has been pushed to the Tudat master. Well done!

**Pull request merged**
