### PR TITLE
Updates to installation wiki and fixed issue with makefile in how to write a wiki wiki

### PR DESCRIPTION
**Pull request by FrankHogervorst**

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Frank,

Thanks! I'll merge this into teh repository. I'm getting some errors on the figures though:

/home/dominic/Software/sphinxTudat/source/tutorials/applicationWalkthroughs/innerSolarSystemPropagation.rst:216: WARNING: image file not readable: tutorials/applicationWalkthroughs/images/InnerSolarSystemOverview.png
/home/dominic/Software/sphinxTudat/source/tutorials/applicationWalkthroughs/innerSolarSystemPropagation.rst:217: WARNING: image file not readable: tutorials/applicationWalkthroughs/images/InnerSolarSystemOrbitsBaryCenter.png
/home/dominic/Software/sphinxTudat/source/tutorials/applicationWalkthroughs/innerSolarSystemPropagation.rst:219: WARNING: image file not readable: tutorials/applicationWalkthroughs/images/InnerSolarSystemOrbits.png
/home/dominic/Software/sphinxTudat/source/tutorials/applicationWalkthroughs/perturbedEarthOrbitingSatellite.rst:150: WARNING: image file not readable: tutorials/applicationWalkthroughs/images/perturbedAndUnperturbed.png
/home/dominic/Software/sphinxTudat/source/tutorials/applicationWalkthroughs/unguidedCapsuleEntry.rst:159: WARNING: image file not readable: tutorials/applicationWalkthroughs/images/apolloResults.png

Do you get these as well?

**Comment by FrankHogervorst** [comment]
No I do not get these errors. Are they located inside an `images` folder in the same folder as the `.rst ` files? (not sure if the repository correctly makes the images folders)

**Comment by DominicDirkx** [comment]
I think some file are missing, my images folder looks like this:

image

**Comment by FrankHogervorst** [comment]
Oops, I forgtot to push the last figures I included. I'll open a new request.

**Pull request merged**
