### PR TITLE
JSON Interface

### PR DESCRIPTION
**Pull request by aleixpinardell**
### Changes Tudat/tudat:development ... aleixpinardell/tudat:json

* Ignore .DS_Store files

      .gitignore
    
* Function `getAtmosphereTablesPath`

      Tudat/Astrodynamics/Aerodynamics/UnitTests/unitTestNRLMSISE00Atmosphere.cpp
      Tudat/Astrodynamics/Aerodynamics/UnitTests/unitTestTabulatedAtmosphere.cpp
      Tudat/InputOutput/basicInputOutput.h
      Tudat/SimulationSetup/EnvironmentSetup/createAtmosphereModel.cpp
      Tudat/SimulationSetup/UnitTests/unitTestEnvironmentModelSetup.cpp
      
* Rename `central_gravity` to `point_mass_gravity`

      Tudat/Astrodynamics/BasicAstrodynamics/accelerationModelTypes.h
      
* Typedef for `std::map< std::string, std::vector< boost::shared_ptr< MassRateModel > > >` as `MassRateModelMap`

      Tudat/Astrodynamics/BasicAstrodynamics/massRateModel.h

* Provide absolute path for non-standard Spice kernels:

      Tudat/Astrodynamics/Gravitation/UnitTests/unitTestGravityFieldVariations.cpp
      Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestSphericalHarmonicPartials.cpp
      
* SH gravity fields coefficients in External directory

      Tudat/Astrodynamics/Gravitation/egm96_coefficients.dat
      Tudat/Astrodynamics/Gravitation/gglp_lpe200_sha.tab
      Tudat/Astrodynamics/Gravitation/jgmro_120d_sha.tab
      Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestSphericalHarmonicPartials.cpp
      Tudat/External/GravityModels/Earth/egm96.txt
      Tudat/External/GravityModels/Earth/ggm02c.txt
      Tudat/External/GravityModels/Earth/ggm02s.txt
      Tudat/External/GravityModels/Mars/jgmro120d.txt
      Tudat/External/GravityModels/Moon/glgm3150.txt
      Tudat/External/GravityModels/Moon/lpe200.txt
      Tudat/InputOutput/basicInputOutput.h
      
* Remove gomp

      Tudat/Astrodynamics/GroundStations/CMakeLists.txt
      
* Fix adding cpp in list of headers

      Tudat/Astrodynamics/Propagators/CMakeLists.txt
      
* Fix typo `body_transational_state_update`

      Tudat/Astrodynamics/Propagators/environmentUpdateTypes.h
      Tudat/Astrodynamics/Propagators/singleStateTypeDerivative.h
      
* CPU time

      Tudat/Astrodynamics/Propagators/integrateEquations.h
      Tudat/Mathematics/NumericalIntegrators/numericalIntegrator.h
      Tudat/Mathematics/NumericalIntegrators/rungeKutta4Integrator.h
      Tudat/Mathematics/NumericalIntegrators/rungeKuttaVariableStepSizeIntegrator.h
      Tudat/SimulationSetup/PropagationSetup/dynamicsSimulator.h
      Tudat/SimulationSetup/PropagationSetup/propagationTermination.cpp
      Tudat/SimulationSetup/PropagationSetup/propagationTermination.h
      Tudat/SimulationSetup/PropagationSetup/propagationTerminationSettings.h
      Tudat/SimulationSetup/PropagationSetup/variationalEquationsSolver.h
      
* Add `DataInterpolationSettings` class

      Tudat/Astrodynamics/Propulsion/UnitTests/unitTestThrustAcceleration.cpp
      Tudat/Mathematics/Interpolators/createInterpolator.h
      Tudat/SimulationSetup/PropagationSetup/accelerationSettings.h
      
* Fix typo `associatedThroustSource_`

      Tudat/Astrodynamics/Propulsion/thrustAccelerationModel.h
      Tudat/SimulationSetup/PropagationSetup/createMassRateModels.cpp
      
* Space weather data to External directory

      Tudat/Astrodynamics/Aerodynamics/sw19571001.txt
      Tudat/External/SpaceWeatherData/sw19571001.txt
      Tudat/InputOutput/basicInputOutput.h
      Tudat/SimulationSetup/UnitTests/unitTestEnvironmentModelSetup.cpp
      
* Fix typo `abberation`

      Tudat/External/SpiceInterface/UnitTests/unitTestSpiceInterface.cpp
      Tudat/External/SpiceInterface/spiceEphemeris.cpp
      Tudat/External/SpiceInterface/spiceEphemeris.h
      Tudat/External/SpiceInterface/spiceInterface.cpp
      Tudat/External/SpiceInterface/spiceInterface.h
      Tudat/SimulationSetup/EnvironmentSetup/createEphemeris.cpp
      Tudat/SimulationSetup/EnvironmentSetup/createEphemeris.h
      
* Make `readMatrixFromFile` templated

      Tudat/InputOutput/CMakeLists.txt
      Tudat/InputOutput/matrixTextFileReader.h
      Tudat/InputOutput/matrixTextFileReader.cpp
      
* Add overload of `writeDataMapToTextFile`

      Tudat/InputOutput/basicInputOutput.h
      
* Add `readEigenVectorMapFromFile` function

      Tudat/InputOutput/mapTextFileReader.h

* More info in the error message when reading tabulated aerodynamics coefficients file

      Tudat/InputOutput/multiDimensionalArrayReader.h
      
* Fix compile error

      Tudat/Mathematics/Interpolators/jumpDataLinearInterpolator.h
      
* Remove `const`

      Tudat/Mathematics/NumericalIntegrators/createNumericalIntegrator.h
      
* Add class `FromFileAerodynamicCoefficientSettings` and make `TabulatedAerodynamicCoefficientSettings<N>` and `TabulatedAerodynamicCoefficientSettings<1>` derive from it

      Tudat/SimulationSetup/EnvironmentSetup/createAerodynamicCoefficientInterface.h

* Add `constantMass` property for `BodySettings`

      Tudat/SimulationSetup/EnvironmentSetup/createBodies.cpp
      Tudat/SimulationSetup/EnvironmentSetup/createBodies.h

* Add class `SphericalHarmonicsModelGravityFieldSettings` to load SH gravity files using the name of a SH model (enumeration)

      Tudat/SimulationSetup/EnvironmentSetup/createGravityField.cpp
      Tudat/SimulationSetup/EnvironmentSetup/createGravityField.h
      Tudat/SimulationSetup/EnvironmentSetup/defaultBodies.cpp
      
* Add optional argument to function `getDefaultBodySettings` to be able to customise interpolation step for ephemeris (was fixed to 300.0 s before)

      Tudat/SimulationSetup/EnvironmentSetup/defaultBodies.cpp

* Move `createAccelerationModelsMap` function to avoid recursive file-inclusion cycle

      Tudat/SimulationSetup/PropagationSetup/createAccelerationModels.cpp
      Tudat/SimulationSetup/PropagationSetup/createAccelerationModels.h
      Tudat/SimulationSetup/PropagationSetup/createNumericalSimulator.cpp
      Tudat/SimulationSetup/PropagationSetup/createNumericalSimulator.h

* Move `createTorqueModelsMap` function to avoid recursive file-inclusion cycle

      Tudat/SimulationSetup/PropagationSetup/createNumericalSimulator.cpp
      Tudat/SimulationSetup/PropagationSetup/createNumericalSimulator.h
      Tudat/SimulationSetup/PropagationSetup/createTorqueModel.cpp
      Tudat/SimulationSetup/PropagationSetup/createTorqueModel.h
      
* Add property `componentIndex_` to `SingleDependentVariableSaveSettings` to allow saving just one of the elements of the vector

      Tudat/SimulationSetup/PropagationSetup/propagationOutput.cpp
      Tudat/SimulationSetup/PropagationSetup/propagationOutput.h
      
* Move `getVectorDependentVariableFunction` above `getDoubleDependentVariableFunction`

      Tudat/SimulationSetup/PropagationSetup/propagationOutput.h
      
* Create class `VariableSettings` to represent Tudat variables and make `SingleDependentVariableSaveSettings` derive from it

      Tudat/SimulationSetup/PropagationSetup/propagationOutputSettings.cpp
      Tudat/SimulationSetup/PropagationSetup/propagationOutputSettings.h
      
* Enable constructing `PropagatorSettings` using a map of `AccelerationSettings`

      Tudat/SimulationSetup/PropagationSetup/propagationSettings.h
      
* Typedef for `std::map< std::string, std::map< std::string, std::vector< boost::shared_ptr< TorqueSettings > > > >` as `SelectedTorqueMap`

      Tudat/SimulationSetup/PropagationSetup/torqueSettings.h
      
* Include `mapTextFileReader` in `tudatSimulationHeader`

      Tudat/SimulationSetup/tudatSimulationHeader.h

* JSON Interface

      Tudat/CMakeLists.txt
      Tudat/JsonInterface/*

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Aleix,

Code compiles fine, but it's getting stuck in an infinite loop in the test_JsonInterfaceDeserialization test. In the getPathForJSONFile function, I add the line:

    std::cout<<"Getting file path "<<file<<" **** "<<basePath<<std::endl;

and get the following:

Getting file path /home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular"
Getting file path .json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"
Getting file path main.json **** "/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json/main.json"

Any ideas?

Cheers,

Dominic

**Comment by DominicDirkx** [comment]
All other tests pass, with one exception: ./test_JsonInterfaceExport

It seems that there is a new line command in the file header that is not the same.

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin/unit_tests$ ./test_JsonInterfaceExport 
Running 2 test cases...
/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/UnitTests/unitTestSupport.h(62): error: in "test_json_export/test_json_export_full_result": check fromFile == manual has failed [{
  "epochsInFirstColumn": false,
  "file": "${TUDAT_ROOT_PATH}/JsonInterface/UnitTests/inputs/unitTestExport/full.txt",
  "header": "Foo",
  "numericalPrecision": 15,
  "onlyFinalStep": false,
  "onlyInitialStep": false,
  "variables": [
    {
      "type": "independent"
    },
    {
      "body": "body",
      "dependentVariableType": "altitude",
      "relativeToBody": "Earth"
    }
  ]
} != {
  "epochsInFirstColumn": false,
  "file": "${TUDAT_ROOT_PATH}/JsonInterface/UnitTests/inputs/unitTestExport/full.txt",
  "header": "Foo\n",
  "numericalPrecision": 15,
  "onlyFinalStep": false,
  "onlyInitialStep": false,
  "variables": [
    {
      "type": "independent"
    },
    {
      "body": "body",
      "dependentVariableType": "altitude",
      "relativeToBody": "Earth"
    }
  ]
}]

*** 1 failure is detected in the test module "Master Test Suite"

**Comment by DominicDirkx** [comment]
Running:

 ./json_interface ../Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json

goes into the infinite loop (as do the other three)

**Comment by DominicDirkx** [comment]
And:

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin$ ./json_interface ~/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json
Getting file path /home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json **** "/home/dominic/Software/tudatBundle/tudat/bin"
The file "/home/dominic/Software/tudatBundle/tudat/bin/home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json" does not exist.
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::canonical: No such file or directory: "/home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json"
Aborted (core dumped)
dominic@dominic-Precisi

**Comment by aleixpinardell** [comment]
Do you have the same problems if you try with `Tudat/JsonInterface/UnitTests/inputs/unitTestSimulationSingleSatellite/main.json`?

**Comment by DominicDirkx** [comment]
I get:

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin$ ./json_interface ~/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestSimulationSingleSatellite/main.json
Getting file path /home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestSimulationSingleSatellite/main.json **** "/home/dominic/Software/tudatBundle/tudat/bin"
The file "/home/dominic/Software/tudatBundle/tudat/bin/home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestSimulationSingleSatellite/main.json" does not exist.
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::canonical: No such file or directory: "/home/dominic/Software/tudaBundle/tudat/Tudat/JsonInterface/UnitTests/inputs/unitTestSimulationSingleSatellite/main.json"
Aborted (core dumped)
dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin$ 

And:

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin$ ./json_interface ../Tudat/JsonInterface/UnitTests/inputs/unitTestDeserialization/modular/main.json


gets stuck in the infinite loop

**Comment by aleixpinardell** [comment]
I updated the code. Could you try again?

**Comment by DominicDirkx** [comment]
Hi Aleix,

Still the same problem, I'm afraid. I've added some extra couts to the code to trace the flow of calls. Attached is the output and the deserialization.cpp file with extra couts.
[jsonTestOutput.txt](https://github.com/Tudat/tudat/files/1360633/jsonTestOutput.txt)
[deserialization.txt](https://github.com/Tudat/tudat/files/1360638/deserialization.txt)

On a positive note, the ./test_JsonInterfaceExport test runs perfectly fine now,

Cheers

**Comment by aleixpinardell** [comment]
I updated the code with some std::cout. Could you run the test again and paste the output?

**Comment by DominicDirkx** [comment]
This is the full output:

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin/unit_tests$ ./test_JsonInterfaceDeserialization 
Running 3 test cases...
$(bodies.json){Earth:Earth,satellite:sat} -> .json

**Comment by aleixpinardell** [comment]
So apparently it's a problem with the regular expression. This is very odd... I wonder why it's not matching "bodies.json" and only ".json".

Could you change line 327 to:
```
std::cout << jsonObject.get< std::string >( ).c_str( ) << " -> " << groups[ 1 ] << std::endl;
```

and see if it's still printing ".json" instead of "bodies.json"?

And if so, could you try changing line 317 to:
```
boost::regex( R"(\$(?:\((.+)\))?(?:\{(.+)\})?)" )
```
It shouldn't make any difference, but who knows. For me both work correctly, also here: https://regex101.com/r/oBasX7/1

**Comment by DominicDirkx** [comment]
Now I get:

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin/unit_tests$ ./test_JsonInterfaceDeserialization 
Running 3 test cases...
$(bodies.json){Earth:Earth,satellite:sat} -> bodies.json

Changing the regex doesn't change the output.

**Comment by aleixpinardell** [comment]
And if you change lines 326 and 329 to:
```
            const std::string file( groups[ 1 ].str( ) );
            const std::string vars( groups[ 2 ].str( ) );
```

**Comment by DominicDirkx** [comment]
Same results, both with the old and new regex....

Perhaps it's good to simplify these functions. There is now a lot of if/else to check certain conditions, and use default settings for certain types of input. I understand why this is in there, and the feature is very nice. At this point, however, I wonder if it's worth it to invest your (limited) time in making this work cross-platform.

**Comment by aleixpinardell** [comment]
And what about
```
            const std::string file = ( std::ostringstream( ) << groups[ 1 ] ).str( );
            const std::string vars = ( std::ostringstream( ) << groups[ 2 ] ).str( );
```

**Comment by DominicDirkx** [comment]
This doesn't compile:

```
11:47:32: Running steps for project TudatBundle...
11:47:32: Starting: "/usr/bin/cmake" --build . --target test_JsonInterfaceDeserialization -- -j12
[  1%] Built target nrlmsise00
[  9%] Built target sofa
[  9%] Built target tudat_electro_magnetism
[ 10%] Built target tudat_system_models
[ 10%] Built target tudat_reference_frames
[ 11%] Built target tudat_relativity
[ 11%] Built target tudat_propulsion
[ 12%] Built target tudat_basic_astrodynamics
[ 12%] Built target tudat_aerodynamics
[ 12%] Built target tudat_basics
[ 12%] Built target tudat_ground_stations
[ 12%] Built target tudat_propagators
[ 14%] Built target tudat_ephemerides
[ 14%] Built target tudat_numerical_integrators
[ 15%] Built target tudat_gravitation
[ 15%] Built target tudat_mission_segments
[ 15%] Built target tudat_earth_orientation
[ 15%] Built target tudat_sofa_interface
[ 15%] Built target tudat_geometric_shapes
[ 15%] Built target tudat_basic_mathematics
[ 15%] Built target tudat_spice_interface
[ 15%] Built target tudat_statistics
[ 16%] Built target tudat_input_output
Scanning dependencies of target json_interface_library
[ 98%] Built target cspice
[ 98%] Building CXX object tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/Support/deserialization.cpp.o
[100%] Built target tudat_simulation_setup
/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/Support/deserialization.cpp:326:79: error: no member named 'str' in 'std::basic_ostream<char>'
            const std::string file = ( std::ostringstream( ) << groups[ 1 ] ).str( );
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/home/dominic/Software/tudatBundle/tudat/Tudat/JsonInterface/Support/deserialization.cpp:329:79: error: no member named 'str' in 'std::basic_ostream<char>'
            const std::string vars = ( std::ostringstream( ) << groups[ 2 ] ).str( );
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.
tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/build.make:86: recipe for target 'tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/Support/deserialization.cpp.o' failed
CMakeFiles/Makefile2:12850: recipe for target 'tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/all' failed
make[3]: *** [tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/Support/deserialization.cpp.o] Error 1
make[2]: *** [tudat/Tudat/JsonInterface/CMakeFiles/json_interface_library.dir/all] Error 2
make[1]: *** [tudat/Tudat/JsonInterface/CMakeFiles/test_JsonInterfaceDeserialization.dir/rule] Error 2
CMakeFiles/Makefile2:11699: recipe for target 'tudat/Tudat/JsonInterface/CMakeFiles/test_JsonInterfaceDeserialization.dir/rule' failed
Makefile:3100: recipe for target 'test_JsonInterfaceDeserialization' failed
make: *** [test_JsonInterfaceDeserialization] Error 2
11:47:35: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"
11:47:35: Elapsed time: 00:03.
```

**Comment by aleixpinardell** [comment]
```
            std::ostringstream fileStream;
            fileStream << groups[ 1 ];
            const std::string file = fileStream.str( );
            std::ostringstream varsStream;
            varsStream << groups[ 2 ];
            const std::string vars = varsStream.str( );
```

**Comment by DominicDirkx** [comment]
Same result...

dominic@dominic-Precision-7510:~/Software/tudatBundle/tudat/bin/unit_tests$ ./test_JsonInterfaceDeserialization 
Running 3 test cases...
$(bodies.json){Earth:Earth,satellite:sat} -> bodies.json

**Comment by DominicDirkx** [comment]
Still getting stuck, despite your last update...

**Comment by aleixpinardell** [comment]
It's very strange... If you add this after line 318, what do you get?
```
if ( groups[ 1 ].matched )
{
    std::cout << groups[ 1 ] << " == " << groups.str( 1 ) << " == " << file << std::endl;
}
```

**Comment by DominicDirkx** [comment]
.json == .json == .json

**Comment by aleixpinardell** [comment]
The special string `"$(file){variables}"` is used to load (parts of) a JSON file into another file.
In the case `"$(bodies.json){Earth:Earth,satellite:sat}"`, it is not working correctly. I don't know if this also happens in other cases. This functionality is used in:
* `test_JsonInterfaceDeserialization`
* `matlabInterface/Examples/InputOutput/ModularInputFiles`
* `matlabInterface/Examples/InputOutput/MultiplePropagations`
* `tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/apolloCapsuleEntryJSON.cpp`
* `tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/lifetimeMaximisation.cpp`

In some  these cases, one of the parts of the string is omitted. For instance, `"$(file)"` is used to load the whole contents of the file and `"${variable}"` is used to "copy" the value of a key defined in the current file. I don't know if the problem also happens for these cases, as the test responsible for testing this, `test_JsonInterfaceDeserialization `, is entering the infinite loop when it encounters the first usage of the special string `"$(file){variables}"`.

The source of the problem is in `Tudat/JsonInterface/Support/deserialization.cpp`, in this part:
```
        boost::smatch groups;
        if ( boost::regex_match( jsonObject.get< std::string >( ), groups,
                                 boost::regex( R"(\$(?:\((.+)\))?(?:\{(.+)\})?)" ) ) )
        {
            const std::string file = groups[ 1 ];
            const std::string vars = groups[ 2 ];
```

If I understood correctly, for the string `"$(bodies.json){Earth:Earth,satellite:sat}"`, the following is happening:
1. Two matches, `"bodies.json"` and `"Earth:Earth,satellite:sat"` are found by `boost::regex_match` and stored in `groups`.
2. `std::cout <<  groups[ 1 ] << std::endl` prints `bodies.json`, as expected.
3. `std::cout <<  file << std::endl` prints `.json`.
4. I'm not sure about what happens if `std::cout <<  groups[ 1 ] << std::endl` is called after `const std::string file = groups[ 1 ]`. In my computer this prints an empty string.
5. We also tried `groups.str( 1 )` and `groups[ 1 ].str( )` which are equivalent.

Here's boost documentation: http://www.boost.org/doc/libs/1_58_0/doc/html/xpressive/user_s_guide.html#boost_xpressive.user_s_guide.accessing_results

I think this part of boost is buggy (or I'm using it incorrectly). If I run this on my computer:
```
std::cout << groups[ 1 ].str( ) << " == " << groups.str( 1 );
```

For the input string `"$(bodies.json){Earth:Earth,satellite:sat}"` I get:
```
bodies.json == bodies.json
```

But for the input string `"$(export/export)"` I get:
```
export/export == 
```

which is very strange.

**Comment by aleixpinardell** [comment]
Btw, I think that when Jacco run the tests a few weeks ago (all passed) this test wasn't included yet. I asked him to download the new code and run the tests, probably he'll encounter the same issue... All the 29 tests are passing on the Mac and Windows I tried.

**Comment by magnific0** [comment]
Just to chime in test_JsonIntefaceExport runs for me without errors. I did have errors building Tudat in general from development and the whole Matlab assisted build didn't work at all. I'll have to dig a bit deeper for that though and report back with something more substantial.

**Comment by DominicDirkx** [comment]
@aleixpinardell 

I also ran the other applications where you say these issues could occur:

./application_ApolloEntryJSON  Error occurs, output is:

Could not load value for ation.variable from file "/home/dominic/Software/jsonBundle/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/apolloCapsuleEntry.json" referenced from file "/home/dominic/Software/jsonBundle/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/apolloCapsuleEntry.json"
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key '
Aborted (core dumped)

./application_LifetimeMaximisation  Error occurs, output is:

Could not load value for [0].variables[0] from file "/home/dominic/Software/jsonBundle/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/lifetimeMaximisation.json" referenced from file "/home/dominic/Software/jsonBundle/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/lifetimeMaximisation.json"
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key '
Aborted (core dumped)

matlabInterface/Examples/InputOutput/MultiplePropagations No problem occurs, output is generated correctly

matlabInterface/Examples/InputOutput/ModularInputFiles Error occurs, output is:

The file "/home/dominic/Software/jsonBundle/tudatBundle/matlabInterface/examples/inputOutput/modularInputFiles/input/WationalPropagator.json" does not exist.
terminate called without an active exception
Aborted (core dumped)

So, 3 out of 4 go wrong, only the matlabInterface/Examples/InputOutput/MultiplePropagation is doing fine...

**Comment by DominicDirkx** [comment]
I've removed the regex that was causing the problems, and replaced it with a bunch of for/if statements. All runs correctly now. I've pushed it to:

https://github.com/DominicDirkx/tudat/tree/aleixpinardell-json

**Comment by aleixpinardell** [comment]
I think that replacing all `boost::regex` with `std::regex` may solve the problem, if you want to give it a try (at some point): https://github.com/aleixpinardell/tudat/tree/json-stdregex

**Pull request closed without merging**
