### PR TITLE
Add unified state model

### PR DESCRIPTION
**Pull request by mvandenbroeck**
Hi,

I would like to provide TUDAT with the code for the conversion from Kepler elements to Unified State Model elements and vice versa.
The files I would like to add to TUDAT are the following:
unifiedStateModelElementConversions.cpp
unifiedStateModelElementConversions.h
unitTestUnifiedStateModelElementConversions.cpp

Furthermore I made changes in the following files to support the above files:
CMakeLists.txt
stateVectorIndices.h

One issue that I still have when executing unitTestUnifiedStateModelElementConversions.cpp is that it gives the following unexpected application output:

C:\tudatBundle_mvdb\tudat\Tudat\Astrodynamics\BasicAstrodynamics\UnitTests\unitTestUnifiedStateModelElementConversions.cpp(172): last checkpoint
C:\tudatBundle_mvdb\tudat\Tudat\Astrodynamics\BasicAstrodynamics\UnitTests\unitTestUnifiedStateModelElementConversions.cpp(442): last checkpoint

I checked online what is meant by "last checkpoint" but I couldn't find a clue relating to my case. Can you have a look at this before adding the code to TUDAT?

Also, this is my first pull request, so if anything is missing please let me know.

Thanks,

Michael
m.m.h.vandenbroeck@student.tudelft.nl
Room 9.03

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Michael,

Great, thanks for the effort of putting this in a neat and proper form! At first glance, the code looks very well structured and robust, I'll get to checking it in detail in the coming 2 weeks,

Cheers,

Dominic

**Comment by DominicDirkx** [comment]
Hi Michiel,

I started looking at the code, and unfortunately I get a few failures in the unit tests:

unknown location(0): fatal error in "testConvertKeplerianToUnifiedStateModelElements": std::runtime_error: When the eccentricity is zero, the argument of pericenter should be zero by definition
Specified argument of pericenter: 6.10865 rad.

```
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(172): last checkpoint
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(367): error in "testConvertUnifiedStateModelToKeplerianElements": Element [3, 0] not within expected tolerance (delta 1.614430e+00): expected 6.108652, was 4.494223, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(367): error in "testConvertUnifiedStateModelToKeplerianElements": Element [4, 0] not within expected tolerance (delta 1.614430e+00): expected 0.261799, was 1.876229, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(367): error in "testConvertUnifiedStateModelToKeplerianElements": Element [5, 0] not within expected tolerance (delta 8.726646e-02): expected 2.967060, was 3.054326, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(386): error in "testConvertUnifiedStateModelToKeplerianElements": Element [3, 0] not within expected tolerance (delta 1.308997e-01): expected 6.108652, was 6.239552, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(386): error in "testConvertUnifiedStateModelToKeplerianElements": Element [4, 0] not within expected tolerance (delta 1.308997e-01): expected 0.261799, was 0.130900, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(386): error in "testConvertUnifiedStateModelToKeplerianElements": Element [5, 0] not within expected tolerance (delta 2.879793e+00): expected 0.174533, was 3.054326, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(404): error in "testConvertUnifiedStateModelToKeplerianElements": Element [3, 0] not within expected tolerance (delta 3.010693e+00): expected 6.108652, was 3.097959, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(404): error in "testConvertUnifiedStateModelToKeplerianElements": Element [4, 0] not within expected tolerance (delta 3.010693e+00): expected 0.261799, was 3.272492, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(404): error in "testConvertUnifiedStateModelToKeplerianElements": Element [5, 0] not within expected tolerance (delta 2.879793e+00): expected 0.174533, was 3.054326, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(423): error in "testConvertUnifiedStateModelToKeplerianElements": Element [4, 0] not within expected tolerance (delta 2.181662e-01): expected 0.261799, was 0.043633, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(423): error in "testConvertUnifiedStateModelToKeplerianElements": Element [5, 0] not within expected tolerance (delta 2.923426e+00): expected 0.174533, was 3.097959, tolerance 1.000000e-14 .
/home/dominicdirkx/Software/tudatClean/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestUnifiedStateModelElementConversions.cpp(442): error in "testConvertUnifiedStateModelToKeplerianElements": Element [5, 0] not within expected tolerance (delta 2.967060e+00): expected 0.174533, was 3.141593, tolerance 1.000000e-14 .
unknown location(0): fatal error in "testConvertUnifiedStateModelToKeplerianElements": std::runtime_error: Pure-retrograde orbit (inclination = pi).
Unified State Model elements cannot be transformed to Kepler elements.
```

The first and last seem to be an issue with the error handling (probably due to rounding). The other ones I'm not sure, let's discuss next week.

The code does look very nice, extensive checks on the entries of the elements, which is great, and very clear commenting. Will be a nice contribution to the code!

Cheers, Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Thanks for looking at the code!
I will have a look at the cause of the failures and pass by some time this week to discuss possible fixes.

Cheers,

Michael

**Comment by mvandenbroeck** [comment]
Hi Dominic,

I found the mistakes in the code,  corrected them and uploaded the new code to GitHub.
The code should be OK now.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

Thanks for the quick updates, unfortunately, there are still some issues with the code, I'll look at it in a bit mroe detail in the next week and get back to you. I did see one curious thing in a couple of places, though:

```
basic_mathematics::Vector6d expectedUnifiedStateModelElements
            = Eigen::VectorXd::Zero( 7 );
```

You are defining a vector of size 6, but are then telling to be set to 7 entries of 0. I'm not sure what the code does with this, but I'm guessing that the exact behaviour is undefined. Since you are defining 7 entries for the unified state model, perhaps all the unified state model vectors need to be size 7? I'm assuming that the 7th entry is present to prevent singulaities,

Dominic

**Comment by DominicDirkx** [comment]
Hi Michael,

I had another quick look at the failures that I get: they seem to be (in part at least) due to inconsistent input. You require that if e=0, then omega = 0 and if i=0, then Omega =0 (to avoid ambiguities). However, your input data does not conform to this standard, since you set:

 ```
   keplerianElements( argumentOfPeriapsisIndex ) = convertDegreesToRadians( 350.0 );
    keplerianElements( longitudeOfAscendingNodeIndex ) = convertDegreesToRadians( 15.0 );
```

Probably the way to best handle this is to add omega and Omega to the (mean or true?) anomaly for e=0 and i=0, respectively, to avoid the ambiguity. I'll think this over a bit more, but probably won't be able to get back to it until next Tuesday.

I have looked at the code in a lot more detail now, and I must say I'm quite impressed by the rigour of all  your tests, you seem to quite rigorously handle all the special cases (angles 0, 180 degrees, etc.). Once these minor issues are resolved, this will make a great contribution to Tudat!

Cheers,

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Thanks for your feedback!
I corrected the issues you informed me about and when I run the new unitTestUnifiedStateModelElementConversions.cpp, the code does not give any failures anymore.

Cheers,

Michael

**Comment by DominicDirkx** [comment]
Great, I've merged your changes on my local branch and the test now passes successfully. There are a few minor issues with regards to coding style, but I'll get to modifying that in the coming days. After that, we can commit this to the repository.

**Pull request merged**
