### PR TITLE
Time type

### PR DESCRIPTION
**Pull request by DominicDirkx**
This pull request adds an extended Time type that provides an accurate representation of time with sub-fs resolution over (nearly) arbitrary time intervals.

Many interfaces have been slightly modified, added or templated as a result of this update. 

Note that this pull request depends on pull request #73

### CODE REVIEW

**Comment by magnific0** [comment]
Hi Dominic,
I have had a look at the new code and it looks really great. I like how detailed you have set up the TimeType and also defined the operators. I have added a few that were missing to make the definition complete. Also I think the operators should be tested in the unit test. I have also added this, but it is very crude for now.
One last comment that I had is that currently TimeType lives directly in the tudat namespace. Shouldn't we put it inside basic_astrodynamics to stick to the convention? I haven't gone through with this change, because I wanted to discuss with you. Is there precedent for this?
Cheers!

**Comment by DominicDirkx** [comment]
Hi Jacco,

Thanks for looking into this in so much detail. You're right, the operators should be tested in more detail. I have updated the unit tests. I also saw that I hadn't added much comments to the Time unit tests overall, I'll add some tomorrow.

Concerning the namespace location: formally you are right. However, if we put it in the basic_mathematics namespace, this is going to make all the code that uses the Time type as a template argument horrible to read (I had it in there at first, but moved it our because it was driving me insane).

Considering the practical consequences, and the very general nature of the Time type, I think it's fine to kee it in the tudat namespace.

**Comment by DominicDirkx** [comment]
Hi Jacco,

I added the extra tests for the comparison operators. If you can check if they pass on your system, and if you agree with the tests themselves, I think we can close this and merge this code.

**Comment by magnific0** [comment]
Hi Dominic,
Thanks for the explanation. I agree that the double namespace is perhaps too much for such a common object. I have the same idea towards basic_mathematics::Vector6d (although this is a simple typedef). Perhaps a list of basic types in the Basics folder is an idea.
Anyway, I have looked at the unit test and it has improved a lot. Thanks! I think it's really complete now. So we can go ahead and merge the code!

**Comment by DominicDirkx** [comment]
Hi Jacco,

That sounds like a great idea, the basic_mathematics::Vector6d type has also been bugging me for a while. 

How would you feel about putting it in the Eigen namespace, instead of tudat::basic_mathematics? It is abusing the namespaces a bit, but it would make a lot more code more readable. I'll merge this code and close the issue, and open a new issue for this,

**Pull request merged**
