### PR TITLE
Trajectory Design module

### PR DESCRIPTION
**Pull request by ifodde**
Done:
- Added input vector to tabulated atmosphere constructor which allows a specific variable-column parring instead of a pre-described order
- Added option to include the ratio of specific heats and specific gas constant in atmosphere file.
- Added new test case in the unit test for a different order of variables.
- New trajectory design module
- Example application added for trajectory design. 

To-do:
- Add an atmosphere file with specific gas constants/specific heat ratios, and add it to the unit tests.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Iosto,

Code looks good, works exactly as intended

I've made few small cosmetic changes that I've pushed here:

https://github.com/DominicDirkx/tudat/tree/ifodde-development

The changes are mostly so that the code complies with Tudat coding standards, and a few other small things. Have a look at the changes, and let me know if anything is unclear. 

When you add the final unit test, could you also update the TabulatedAtmosphereSettings class, and documentation?

Have a nice Easter,

Dominic

**Comment by DominicDirkx** [comment]
Hi Iosto,

I could've sworn that we finalized this code already, but I see it isn't merged yet. Could you refresh my memory what the status is?

Dominic

**Comment by ifodde** [comment]
Hey Dominic,

In my memory, I also thought this should've already been merged. I thought I could add the things mentioned above after it was merged, but maybe you wanted it to be done before it is merged? I could add those changes to the tabulated atmosphere together with the MGA trajectory design so that after I commit that to this branch, it would appear in this pull request. Let me know what you think.

Iosto

**Comment by DominicDirkx** [comment]
Hi Iosto,

Somehow it's good to see that we have the same wrong recollection of this :) 

If possible, I would prefer adding the MGA and tabulated atmosphere updates in different pull requests/branches. If it's already all on a single branch, it's fine to combine them into a single pull request, though. It's not important enough to make the effort to separate it again.

Dominic

**Comment by ifodde** [comment]
Hey @DominicDirkx ,

the trajectory design module first iteration can be viewed here (the branch for the tabulated atmosphere is the same so the commits for those files are also here). Please let me know what you think needs to be altered/added before it can be merged.

Cheers,
Iosto

**Comment by DominicDirkx** [comment]
Hi Iosto,

Thanks, code looks great. I think we can get this into the repository pretty soon. There are a few small points that should be addressed before then:

- The new code in the TrajectoryDesign folder is missing a bunch of Doxygen comments, in particular the \param and \return entries. These should be present for all functions (free functions and class functions) in the .h files. For many of the classes, this will be a matter of copy-paste once you've done one of them.
- The file headers should be updated to the latest one (only in .h files, not in .cpp files, where it should be removed altogether. Where relevant, any notes such as literature references should be kept.
- A number of include statements in the unit tests still refer to old code. After replacing:

#include "SpaceTrajectories/

with:

#include "Tudat/Astrodynamics/TrajectoryDesign/

it all ran fine (see https://github.com/DominicDirkx/tudat/tree/ifodde-development)
- I made a few small modifications to the CMakeLists (see link above).
- A few small tests for the new ratio of specific heat ratio and gas constant functionality in the tabulated atmosphere should be added. This can be very small, just to check that it is indeed behaving as it should

Dominic

**Comment by ifodde** [comment]
Hi Dominic,

your comments have been added to the branch, please let me know if there is something else that needs to change.

Cheers,
Iosto

**Pull request merged**
