### PR TITLE
Aerothermodynamics functions now included in the Aerodynamics module.

### PR DESCRIPTION
**Pull request by agonzalezpuerta**
First iteration of the aerothermodynamics functions. Only aerodynamic load (aka load factor) and heat flux were added. Heat load should be the integral of the heat flux, so I suppose that should go somewhere else. Cheers

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Could you post the link to the exact reference for the heating models? 

Do you also happen to have a literature value for a unit test, i.e. a heating value for given input conditions.

**Comment by agzrocket** [comment]
Source: http://arc.aiaa.org/doi/abs/10.2514/8.7517?journalCode=jasps
I will come back to you with reference values asap.

**Comment by DominicDirkx** [comment]
I've had a look through the code, made some small modifications, and updated the dependent variable outputting as per issue #89, see branch:

https://github.com/DominicDirkx/tudat/tree/agzrocket-aerothermodynamics

The new functionality does not yet have proper unit tests. The most difficult part for this will be the heating. Limit cases will be easy to test, the full functionality would be most easily tested with literature values, though.

**Comment by agzrocket** [comment]
I found a few issues when requesting the additional outputs in this branch from a MultiTypePropagator.

1. Run-time error when requesting "stagnation_point_heat_flux_dependent_variable":
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error when getting acceleration between bodies, no translational dynamics models by  acting on Sphynx are found
The program has unexpectedly finished.

2. Run-time error when requesting "geodetic_latitude_dependent_variable":
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error when getting acceleration between bodies, no translational dynamics models by  acting on Sphynx are found
The program has unexpectedly finished.

**Comment by DominicDirkx** [comment]
Could you append the main file you use to generate this output?

**Comment by agzrocket** [comment]
I did some further testing and the mentioned run time errors can also be replicated when using the ApolloEntry application (which uses the TranslationalStatePropagatorSettings). Please see the appended source file. Note that it is simply the standard ApolloEntry code with the additional dependent variables.

`/*    Copyright (c) 2010-2016, Delft University of Technology
 *    All rigths reserved
 *
 *    This file is part of the Tudat. Redistribution and use in source and
 *    binary forms, with or without modification, are permitted exclusively
 *    under the terms of the Modified BSD license. You should have received
 *    a copy of the license with this file. If not, please or visit:
 *    http://tudat.tudelft.nl/LICENSE.
 */

#include <Tudat/SimulationSetup/tudatSimulationHeader.h>

#include <Tudat/Astrodynamics/Aerodynamics/UnitTests/testApolloCapsuleCoefficients.h>

#include <SatellitePropagatorExamples/applicationOutput.h>

//! Execute propagation of orbits of Apollo during entry.
int main( )
{
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////            USING STATEMENTS              //////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


    using namespace tudat::ephemerides;
    using namespace tudat::interpolators;
    using namespace tudat::numerical_integrators;
    using namespace tudat::spice_interface;
    using namespace tudat::simulation_setup;
    using namespace tudat::basic_astrodynamics;
    using namespace tudat::orbital_element_conversions;
    using namespace tudat::propagators;
    using namespace tudat::aerodynamics;
    using namespace tudat::basic_mathematics;
    using namespace tudat::input_output;
    using namespace tudat;

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////            CREATE ENVIRONMENT            //////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Load Spice kernels.
    spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "pck00009.tpc" );
    spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "de-403-masses.tpc" );
    spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "de421.bsp" );

    // Set simulation start epoch.
    const double simulationStartEpoch = 0.0;

    // Set simulation end epoch.
    const double simulationEndEpoch = 3100.0;

    // Set numerical integration fixed step size.
    const double fixedStepSize = 1.0;

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////            CREATE ENVIRONMENT            //////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Define simulation body settings.
    std::map< std::string, boost::shared_ptr< BodySettings > > bodySettings =
            getDefaultBodySettings( { "Earth" }, simulationStartEpoch - 10.0 * fixedStepSize,
                                    simulationEndEpoch + 10.0 * fixedStepSize );  
    bodySettings[ "Earth" ]->ephemerisSettings = boost::make_shared< simulation_setup::ConstantEphemerisSettings >(
                basic_mathematics::Vector6d::Zero( ), "SSB", "J2000" );
    bodySettings[ "Earth" ]->rotationModelSettings->resetOriginalFrame( "J2000" );

    // Create Earth object
    simulation_setup::NamedBodyMap bodyMap = simulation_setup::createBodies( bodySettings );

    // Create vehicle objects.
    bodyMap[ "Apollo" ] = boost::make_shared< simulation_setup::Body >( );

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////             CREATE VEHICLE            /////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


    // Create vehicle aerodynamic coefficients
    bodyMap[ "Apollo" ]->setAerodynamicCoefficientInterface(
                unit_tests::getApolloCoefficientInterface( ) );
    bodyMap[ "Apollo" ]->setConstantBodyMass( 5.0E3 );

    // Finalize body creation.
    setGlobalFrameBodyEphemerides( bodyMap, "SSB", "J2000" );

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////             CREATE ACCELERATIONS            ///////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Define propagator settings variables.
    SelectedAccelerationMap accelerationMap;
    std::vector< std::string > bodiesToPropagate;
    std::vector< std::string > centralBodies;

    // Define acceleration model settings.
    std::map< std::string, std::vector< boost::shared_ptr< AccelerationSettings > > > accelerationsOfApollo;
    accelerationsOfApollo[ "Earth" ].push_back( boost::make_shared< SphericalHarmonicAccelerationSettings >( 4, 0 ) );
    accelerationsOfApollo[ "Earth" ].push_back( boost::make_shared< AccelerationSettings >( aerodynamic ) );
    accelerationMap[  "Apollo" ] = accelerationsOfApollo;

    bodiesToPropagate.push_back( "Apollo" );
    centralBodies.push_back( "Earth" );

    // Create acceleration models
    basic_astrodynamics::AccelerationMap accelerationModelMap = createAccelerationModelsMap(
                bodyMap, accelerationMap, bodiesToPropagate, centralBodies );
    bodyMap.at( "Apollo" )->getFlightConditions( )->getAerodynamicAngleCalculator( )->setOrientationAngleFunctions(
                boost::lambda::constant( 30.0 * mathematical_constants::PI / 180.0 ) );

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////             CREATE PROPAGATION SETTINGS            ////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Set spherical elements for Apollo.
    Vector6d apolloSphericalEntryState;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::radiusIndex ) = spice_interface::getAverageRadius( "Earth" ) + 120.0E3;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::latitudeIndex ) = 0.0;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::longitudeIndex ) = 1.2;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::speedIndex ) = 7.8E3;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::flightPathIndex ) = -0.8 * mathematical_constants::PI / 180.0;
    apolloSphericalEntryState( SphericalOrbitalStateElementIndices::headingAngleIndex ) = 0.6;

    // Convert apollo state from spherical elements to Cartesian elements.
    const Vector6d systemInitialState = convertSphericalOrbitalToCartesianState(
                apolloSphericalEntryState );


    // Define list of dependent variables to save.
    std::vector< boost::shared_ptr< SingleDependentVariableSaveSettings > > dependentVariables;
    dependentVariables.push_back(
                boost::make_shared< SingleDependentVariableSaveSettings >( mach_number_dependent_variable, "Apollo" ) );
    dependentVariables.push_back(
                boost::make_shared< SingleDependentVariableSaveSettings >( altitude_dependent_variable,
                                                                           "Apollo", "Earth" ) );
//    dependentVariables.push_back(
//                boost::make_shared< SingleDependentVariableSaveSettings >( total_aerodynamic_g_load_variable, "Apollo" ) );

//    dependentVariables.push_back(
//                boost::make_shared< SingleDependentVariableSaveSettings >( stagnation_point_heat_flux_dependent_variable, "Apollo" ) );

    dependentVariables.push_back(
                boost::make_shared< SingleDependentVariableSaveSettings >( geodetic_latitude_dependent_variable, "Apollo" ) );

    dependentVariables.push_back(
                boost::make_shared< SingleAccelerationDependentVariableSaveSettings >(
                    aerodynamic, "Apollo", "Earth", 1 ) );


    // Create propagation settings.
    boost::shared_ptr< TranslationalStatePropagatorSettings< double > > propagatorSettings =
            boost::make_shared< TranslationalStatePropagatorSettings< double > >
            ( centralBodies, accelerationModelMap, bodiesToPropagate, systemInitialState,
              boost::make_shared< PropagationDependentVariableTerminationSettings >(
                  boost::make_shared< SingleDependentVariableSaveSettings >(
                      altitude_dependent_variable, "Apollo", "Earth" ), 25.0E3, true ),
              cowell, boost::make_shared< DependentVariableSaveSettings >( dependentVariables ) );
    boost::shared_ptr< IntegratorSettings< > > integratorSettings =
            boost::make_shared< IntegratorSettings< > >
            ( rungeKutta4, simulationStartEpoch, fixedStepSize );


    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////             PROPAGATE ORBIT            ////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


    // Create simulation object and propagate dynamics.
    SingleArcDynamicsSimulator< > dynamicsSimulator(
                bodyMap, integratorSettings, propagatorSettings, true, false, false );

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////        PROVIDE OUTPUT TO FILE                        //////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


    // Write Apollo propagation history to file.
    writeDataMapToTextFile( dynamicsSimulator.getEquationsOfMotionNumericalSolution( ),
                            "apolloPropagationHistory.dat",
                            tudat_applications::getOutputPath( ),
                            "",
                            std::numeric_limits< double >::digits10,
                            std::numeric_limits< double >::digits10,
                            "," );
    writeDataMapToTextFile( dynamicsSimulator.getDependentVariableHistory( ),
                            "apolloDependentVariableHistory.dat",
                            tudat_applications::getOutputPath( ),
                            "",
                            std::numeric_limits< double >::digits10,
                            std::numeric_limits< double >::digits10,
                            "," );

    // Final statement.
    // The exit code EXIT_SUCCESS indicates that the program was successfully executed.
    return EXIT_SUCCESS;}
`

**Comment by DominicDirkx** [comment]
Hi Alejandro,

These issues seem to be because

- You need to specify a 'secondary body' for outputting the g load (e.g. the body possessing the atmosphere that exerts the g-load):

```
- dependentVariables.push_back(
                boost::make_shared< SingleDependentVariableSaveSettings >( total_aerodynamic_g_load_variable, "Apollo", "Earth" ) );
```

- To use the stagnation point heat flux, you need to add a 'VehicleSystems' member to the Body object of the vehicle (see Astrodynamics/SystemModels). In this object, you need to set the emmissivity and nose radius.

- I had forgotten to define the size of the geodetic latitude, pull the latest modifications from my github branch

Let me know if this resolves the issues,

Dominic

**Comment by agzrocket** [comment]
Thanks this seemed to solve the problem! 

Alejandro

**Comment by agzrocket** [comment]
One additional issue:

- Selecting the longitude_angle output prints the wrong values. This can be replicated with the Apollo_Entry application. An initial longitude of 1.2 rad as set in the example, leads to a printed longitude of 2.59 rad.

**Comment by DominicDirkx** [comment]
Hi Alejandro,

I think this is a small inconsistency in the Apollo example: the initial state is given in ECEF, not ECI, if you define the Vehicle's initial state as:

   ```
 Vector6d systemInitialState = convertSphericalOrbitalToCartesianState(
                apolloSphericalEntryState );

    boost::shared_ptr< ephemerides::RotationalEphemeris > earthRotationalEphemeris =
            bodyMap.at( "Earth" )->getRotationalEphemeris( );
    systemInitialState = transformStateToGlobalFrame( systemInitialState, simulationStartEpoch, earthRotationalEphemeris );
```

It seems to work

**Comment by DominicDirkx** [comment]
Hi Alejandro,

I've added some unit tests for the heating/equilibrium temperature. I've also added some extra tests for the dependent variable saving and commenting all the new stuff, see my branch:

https://github.com/DominicDirkx/tudat/tree/agzrocket-aerothermodynamics

Could you check if the code runs properly (e.g. all unit tests pass) on your machine, and give the small changes I've made a quick look? If you're happy with everything, I'll push this to the master,

Cheers,

Dominic

**Comment by agzrocket** [comment]
Hi Dominic,

Sure, I will review the additions by the end of the week. I will let you know once it is done.

Alejandro

**Comment by agzrocket** [comment]
Hi Dominic,

I have retrieved the following compile information. I will review the aerothermodynamics tests tomorrow.

`The following tests FAILED:
	  6 - test_TabulatedAerodynamicCoefficients (Failed)
	 57 - test_ReferenceFrameTransformations (Failed)
	 75 - test_DependentVariableOutput (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8
17:41:49: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"`

**Comment by DominicDirkx** [comment]
Hi Alejandro,

Hmm, looks like something from the last commit(s) is not really working well for you. There should be a test log file in your build folder. 

For me it's in build/Testing/Temporary/LastTest.log

Note that this file gets overwritten everytime you run the unit tests. If you post this file here, I'll have a look to see what the issue is,

**Comment by agzrocket** [comment]
Hi Dominic,
Here is the log file.
[LastTest.log.zip](https://github.com/Tudat/tudat/files/626695/LastTest.log.zip)

**Comment by DominicDirkx** [comment]
Hi Alejandro,

Thanks, the errors seem to be from three distinct causes:

- the reference frame transformation fail due to a tolernace that is slightly too low, most likely due to different rounding errors on your system
- the test_TabulatedAerodynamicCoefficients fails because nrlmsise seems to be turned off (at least in part). In your CMakeCache, there should be a line:

USE_NRLMSISE00:BOOL=OFF

Changing the 'OFF' to 'ON' should fix this.

- the test_DependentVariableOutput is crashing without giving a specific reason. I've updated my branch of your code 

https://github.com/DominicDirkx/tudat/tree/agzrocket-aerothermodynamics

to the latest Tudat master, maybe there were some inconsistencies. Try running the tests with the updated code. If the test_DependentVariableOutput is still failing, cold you attach a stack trace from the debugger here? If you're not sure, how to get this output, just leave a note here and I'll provide some instructions.

**Comment by agzrocket** [comment]
Hi Dominic,
I did some further tests and these were the results:
- Turning on NRLMSISE-00 solves the failure of test_TabulatedAerodynamicCoefficients. I recall deliberately turning this module off for some compatibility issues with other part of my code.
- Updating the agzrocket-aerothermodynamics branch did not solve the other failures. Here is the stack trace for test_DependentVariableOutput:

> 1  int tudat::basic_mathematics::findNearestLeftNeighbourUsingHuntingAlgorithm<double>(double, int, std::vector<double> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0x5bff31       
2  tudat::interpolators::HuntingAlgorithmLookupScheme<double>::findNearestLowerNeighbour(double)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0x5bfff3       
3  tudat::interpolators::MultiLinearInterpolator<double, Eigen::Matrix<double, 6, 1, 0, 6, 1>, 3>::interpolate(std::vector<double> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0x65a47f       
4  tudat::aerodynamics::AerodynamicCoefficientGenerator<3, 6>::updateCurrentCoefficients(std::vector<double> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0x65a594       
5  tudat::aerodynamics::TrimOrientationCalculator::getPerturbedMomentCoefficient(double, std::vector<double> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0x65fd18       
6  tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttack(std::vector<double>)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0x660636       
7  tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttackFromFunction(boost::function<std::vector<double> ()>)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0x5d1dcd       
8  boost::detail::function::function_obj_invoker0<boost::_bi::bind_t<double, boost::_mfi::mf1<double, tudat::aerodynamics::TrimOrientationCalculator, boost::function<std::vector<double> ()>>, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<tudat::aerodynamics::TrimOrientationCalculator>>, boost::_bi::value<boost::function<std::vector<double> ()>>>>, double>::invoke(boost::detail::function::function_buffer&)                                                                                                                                                                                                                                                                0x5caba9       
9  tudat::reference_frames::AerodynamicAngleCalculator::update(double, bool)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0x69672e       
10 tudat::aerodynamics::FlightConditions::updateConditions(double)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0x65e603       
11 tudat::propagators::EnvironmentUpdater<double, double>::updateEnvironment(double, std::unordered_map<tudat::propagators::IntegratedStateType, Eigen::Matrix<double, -1, 1, 0, -1, 1>> const&, std::vector<tudat::propagators::IntegratedStateType> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                   0x58a4f6       
12 tudat::propagators::DynamicsStateDerivativeModel<double, double>::computeStateDerivative(double, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0x5b1920       
13 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<Eigen::Matrix<double, -1, -1, 0, -1, -1>, boost::_mfi::mf2<Eigen::Matrix<double, -1, -1, 0, -1, -1>, tudat::propagators::DynamicsStateDerivativeModel<double, double>, double, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<tudat::propagators::DynamicsStateDerivativeModel<double, double>>>, boost::arg<1>, boost::arg<2>>>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, double, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&>::invoke(boost::detail::function::function_buffer&, double, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&)                  0x557758       
14 boost::detail::function::function_obj_invoker2<boost::function<Eigen::Matrix<double, -1, -1, 0, -1, -1> (double, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&)>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&>::invoke(boost::detail::function::function_buffer&, double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)                                                                                                                                                                                                                                                                                                                 0x56bb96       
15 boost::function2<Eigen::Matrix<double, -1, 1, 0, -1, 1>, double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&>::operator()(double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&) const                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0x578f9b       
16 tudat::numerical_integrators::RungeKutta4Integrator<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>>::performIntegrationStep(double)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0x579223       
17 void tudat::propagators::integrateEquations<Eigen::Matrix<double, -1, 1, 0, -1, 1>, double>(boost::shared_ptr<tudat::numerical_integrators::NumericalIntegrator<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>>>, double, boost::function<bool (double)>, std::map<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>>&, std::map<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>>&, boost::function<Eigen::Matrix<double, -1, 1, 0, -1, 1> ()>, int, double)                                                                                                                                                                                             0x586cf0       
18 void tudat::propagators::integrateEquations<Eigen::Matrix<double, -1, 1, 0, -1, 1>, double>(boost::function<Eigen::Matrix<double, -1, 1, 0, -1, 1> (double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)>, std::map<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>, boost::shared_ptr<tudat::numerical_integrators::IntegratorSettings<double>>, boost::function<bool (double)>, std::map<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>>&, boost::function<Eigen::Matrix<double, -1, 1, 0, -1, 1> ()>, double)                                                                                                                                  0x59bd5d       
19 tudat::propagators::SingleArcDynamicsSimulator<double, double>::integrateEquationsOfMotion(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0x59ce98       
20 tudat::unit_tests::test_dependent_variable_output::testDependentVariableOutput::test_method()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0x54fec4       
21 tudat::unit_tests::test_dependent_variable_output::testDependentVariableOutput_invoker()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0x55488e       
22 boost::unit_test::ut_detail::callback0_impl_t<boost::unit_test::ut_detail::unused, void ( *)()>::invoke()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0x555a67       
23 boost::unit_test::ut_detail::callback0_impl_t<int, boost::unit_test::(anonymous namespace)::zero_return_wrapper_t<boost::unit_test::callback0<boost::unit_test::ut_detail::unused>>>::invoke()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               0x84ec11       
24 boost::execution_monitor::catch_signals(boost::unit_test::callback0<int> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             0x853b46       
25 boost::execution_monitor::execute(boost::unit_test::callback0<int> const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0x8542d3       
26 boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::unit_test::test_case const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             0x84ed3f       
27 boost::unit_test::framework_impl::visit(boost::unit_test::test_case const&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0x84a35e       
28 boost::unit_test::traverse_test_tree(boost::unit_test::test_suite const&, boost::unit_test::test_tree_visitor&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0x83dbdc       
29 boost::unit_test::traverse_test_tree(boost::unit_test::test_suite const&, boost::unit_test::test_tree_visitor&)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0x83dbcd       
30 boost::unit_test::framework::run(unsigned long, bool)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0x845a44       
31 boost::unit_test::unit_test_main(boost::unit_test::test_suite * ( *)(int, char * *), int, char * *)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0x8221f7       
32 __libc_start_main                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           libc-start.c 291 0x7ffff718d830 
33 _start                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0x54d089

**Comment by DominicDirkx** [comment]
Thanks for the trace! I've uploaded some debugging output to the branch, could you update your local code with these changes, run test_DependentVariableOutput and attach the output here? (just the regular output, not the stack trace). Thanks!

**Comment by DominicDirkx** [comment]
I'm closing this issue, as it is encompassed by the more comprehensive code check #113

**Pull request closed without merging**
