### PR TITLE
Added velocity based LVLH to inertial frame transformation

### PR DESCRIPTION
**Pull request by mvandenbroeck**
Two functions were added to referenceFrameTransfomations.cpp and referenceFrameTransformations.h:

- A function that gives the transformation quaternion to rotate a vector in the body-centered velocity based LVLH frame (TNW frame) to the inertial (I) frame. 
Inputs: Cartesian state of body wrt central body, Cartesian state of central body wrt inertial frame, a bool to specify whether the N axis of the TNW frame is pointing away from the central body or not (pointing away from central body by default).
Output: transformation quaternion.

- A function that gives the transformation matrix to rotate a vector in the body-centered velocity based LVLH frame (TNW frame) to the planet-fixed (planetocentric) frame. The N axis in the TNW frame is pointing to the inside of the orbit.
Input: Keplerian state of body wrt central body.
Output: transformation matrix.

Both functions are accompanied by unitTests.

Cheers,

Michael

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Michael, could you attach your Matlab script used for the unit test here?

**Comment by mvandenbroeck** [comment]
Hi Dominic, here is the Matlab file. I had to put in in a .txt file though.
.m files are not allowed as attachments.

[velocityBasedLvlhToPlanetocentricFrameTransformation.txt](https://github.com/Tudat/tudat/files/601990/velocityBasedLvlhToPlanetocentricFrameTransformation.txt)

Cheers,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

Thanks! I've gone through the code, made some small corrections and added an extra extensive unit test, which verifies whether all properties that one would expect of the rotations hold true.

Also, I've added an extra check to the test from Keplerian elements, so that the conversion from Cartesian elements is also computed. Both results are the same within numerical precision. 

I've pushed all changes to my

https://github.com/DominicDirkx/tudat/tree/mvandenbroeck-master

branch. If you have any more questions/comments on this code, let me know. If not, I'll merge it into the Tudat master.

Dominic

**Comment by DominicDirkx** [comment]
HI Michael,

Thanks for the check, code has now been added to the Tudat master!

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Thanks for the addition!

Michael

**Pull request merged**
